blogapp/urls.py
from django.urls import path
from blogapp import views 

app_name = 'blogapp'

urlpatterns = [
    path('list/',views.PostListView.as_view(),name='post_list'),
    path('create/',views.PostCreateView.as_view(),name='post_new'),
    path('post/detail/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/delete/<int:pk>',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/edit/<int:pk>',views.PostUpdateView.as_view(),name='post_edit'),
    path('add_comment/<int:pk>',views.add_comment_to_post,name='addcomment'),
    path('delete_comment/<int:pk>',views.comment_remove,name='commentdelete'),
    
]

blogsite_dbms_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as v
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='base'),
    path('blog/',include("blogapp.urls",namespace="blogapp")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/login/',v.LoginView.as_view(template_name='templates/login.html'),name='login'),
    path('accounts/logout/',v.LogoutView.as_view(template_name='templates/base.html'),name='logout'),
]

blogapp/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=264)
    text = models.TextField(default='')
    published_date = models.DateTimeField(blank=True)

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        self.published_date = timezone.now()
        super().save(*args,**kwargs) 
    
    def get_absolute_url(self):
        return reverse('blogapp:post_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ["-published_date"]


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    author = models.CharField(max_length=264)
    text = models.TextField()
    published_date = models.DateTimeField(blank=True)

    def __str__(self):
        return self.text

    
    

blogapp/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author','title', 'text',)

        


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

       

blogapp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import Post,Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm,CommentForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.

class PostListView(generic.ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by("-published_date")

class PostCreateView(LoginRequiredMixin,generic.CreateView):
    
    redirect_field_name = 'blogapp:post_list'
    model = Post
    form_class = PostForm

class PostDetailView(generic.DetailView):
    model = Post

class PostUpdateView(LoginRequiredMixin,generic.UpdateView):
   
    redirect_field_name = 'blogapp:post_list'
    model = Post
    form_class = PostForm

class PostDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blogapp:post_list')

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.published_date = timezone.now()
            comment.post = post
            comment.save()
            return redirect('blogapp:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blogapp/comment_form.html', {'form': form})


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blogapp:post_detail', pk=post_pk)

blogsite_dbms_project/views.py
from django.shortcuts import render


def index(request):
    return render(request,"base.html",{})
    

blogapp/templates/blogapp/comment_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Post Comment</button>
    </form>
{% endblock %}

blogapp/templates/blogapp/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

blogapp/templates/blogapp/post_detail.html
{% extends 'base.html' %}

{% block content %}


        <h1 class='posttitle loader'>{{ post.title }}</h1>

       
            <div class="date postdate">
                {{ post.published_date }}
            </div>


      <p class='postcontent' >{{ post.text|safe|linebreaksbr }}</p>


      {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'blogapp:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
          <a class="btn btn-primary" href="{% url 'blogapp:post_delete' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
      {% endif %}



  <hr>
  <a class="btn btn-primary btn-comment" href="{% url 'blogapp:addcomment' pk=post.pk %}">Add comment</a>
  <div class="container">


  {% for comment in post.comment_set.all %}
  <br>
     

             
              

          <p>{{ comment.text|safe|linebreaks }}</p>
          <p>Posted by: <strong>{{ comment.author }}  {{ comment.created_date }}</strong></p>
          {% if user.is_authenticated  %}
                  <a class="btn btn-default" href="{% url 'blogapp:commentdelete' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
           {% endif %}

      
   {% endfor %}
   
   {% if post.comment_set.all.count == 0 %}
   <p>No comments  </p>
       
   {% endif %}
       
  
</div>

{% endblock %}

blogapp/templates/blogapp/post_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>

    <form method="POST" style="color: teal;" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>

   
{% endblock %}

blogapp/templates/blogapp/post_list.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="centerstage">
    <p style="color: crimson; font-size: larger;">Post List</p>
    <br>
    <div class="card" style="width: 90%; ">

        <ul class="list-group list-group-flush">
            {% for post in post_list %}
                <li class="list-group-item"><a style="color: rgb(240, 99, 18);font-size: large;" href="{% url 'blogapp:post_detail' pk=post.pk %}">{{ post.title }}</a>{% if post == post_list.0 %}<span class="badge badge-secondary">New</span>{% endif %}</li>
            {% endfor %}
        </ul>
      </div>    
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
  <title>Blog Project</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <style>
    .con {
      background-color: rgb(253, 237, 237);
      text-align: center;
      color: rgb(235, 67, 25);
      
      width: 100%;
      height: 150px;
      padding-top: 4px;
      box-sizing: border-box;
      box-shadow: 4px 7px  5px grey;
    }

    body {
     
      color: rgb(248, 54, 28);
    }
  </style>


</head>



<body>


  <nav class="navbar navbar-default techfont custom-navbar" >
    <div class="container">


      <ul class="nav navbar-nav">
        <li><a class='navbar-brand bigbrand' href="{% url "base" %}"> BlogSite</a></li>
        <li><a href="{% url 'blogapp:post_list' %}"> Post list</a></li>


      </ul>

      <ul class="nav navbar-nav navbar-right">

        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'blogapp:post_new' %}">New Post</a>
        </li>


        <li>
          <a href="{% url 'logout' %}">Log out</a>
        </li>

        <li>
          <a>Welcome: {{ user.username }}</a>
        </li>
        {% else %}
        <li><a class='nav navbar-right' href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span>
            Login</a></li>
        {% endif %}

      </ul>
    </div>
  </nav>

  <div class="container">
    
     
      

      {# The actual blog posts#}
      <div class="content container">
        
              {% block content %}
              {% endblock %}
   
     
    </div>
  </div>
</body>

</html>